spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devclass?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:    # 본인 비밀번호 입력
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

server:
  port: 8080